config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :topics, only: [:show, :index]
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout',sign_up:'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do 
    member do
      get :toggle_status
    end  
  end  


  
  # ACRemove mount ActionCable.server => '/cable' #this create the web-socket connection

  root to: 'pages#home'

end

app/views/shared/_application_footer.html.erb
    <div class="mastfoot">
      <div class="inner text-muted ">
        <p style="text-align: center;" class=" h1-style"><%= copyright_generator %> </p>
        
      </div>
    </div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix ">
  <div class="inner">
    <h3 class="masthead-brand "><%= link_to "Peter Tran", root_path, style: "text-decoration: none;" %>
 </h3>
    <nav class="nav nav-masthead app-nav mt-1">

      <%= link_to "Home", root_path, class: 'nav-link' %>
      <%= link_to "About Me", about_me_path, class: 'nav-link' %>
      <%= link_to "Contact", contact_path, class: 'nav-link' %>
      <%= link_to "Tweets",  tech_news_path, class: 'nav-link' %>
      <%= link_to "Blog", blogs_path, class: 'nav-link' %>
      <%= link_to "Portfolio", portfolios_path, class: 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p> <%= render "shared/application_footer" %> <!-- concern for copyright footer --></p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_header.html.erb
  <div class="blog-header">
    <div class="container">
      <center>
        <h1 class="blog-title">Inside My Head..</h1>
              <h2 class="lead blog-description  align-items-end ">My observations as a web developer.</h2>

      </center>
      <br>
   

      <span><%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %></span>
      

    </div>
  </div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark  bg-dark">
  <div class="container">
     <%= link_to "Peter Tran", root_path, class: "navbar-brand ", style: "  text-decoration: none;"%> 

     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav ml-auto ">
           <%= link_to "Home", root_path, class: "nav-link " %>            
           <%= link_to "About", about_me_path, class: "nav-link" %>
           <%= link_to "Contact", contact_path, class: "nav-link" %>
           <%= link_to "Tweets",  tech_news_path, class: 'nav-link' %>
           <%= link_to "Blogs", blogs_path, class: "nav-link" %>           
           <%= link_to "Portfolio", portfolios_path, class: "nav-link"  %>
           <%= login_helper 'nav-link' %>  
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3  blog-sidebar mt-5">
  <div class="sidebar-module sidebar-module-inset">
     <%= image_tag "logo.png", alt: "profile image", class: 'img-fluid' %>

  </div>




  <div class="sidebar-module ">
    <center>
      <h4><%= link_to "Topics", topics_path %>
      </h4>
      <h6 class="small">(Click for More)</h6>
      <hr>
        <% @side_bar_topics.each do |topic| %>
          <p><%= link_to topic.title, topic_path(topic)%> </p>
        <% end %>

    </center>  
  </div>



  <div class="sidebar-module">
    <center>
      <h4 class="blog-about-section">Find Me At</h4>
      <hr>

      <ol class="list-unstyled">
        <li> <h5><a href="mailto:petertran198@gmail.com?subject=PortfolioContact" "email me" class="pulse-grow"><%=fa_icon "envelope",class: "icon pulse"%> </a></h5></li>
        <li><h5><a href="https://github.com/Petertran198" target="_blank" rel="noopener noreferrer"><%=fa_icon "github",class: "icon pulse"%></a></h5></li>
        <li><h5><a href="https://www.linkedin.com/in/petertran-web-developer/" target="_blank" rel="noopener noreferrer"><%=fa_icon "linkedin-square",class: "icon pulse"%></a></h5></li>
      </ol>
    </center>
  </div>

   
</div>

app/views/shared/_nav.html.erb
<div class= "<%= location %>">
       <div><%= link_to "Home", root_path %></div>
       <div><%= link_to "About", about_me_path %></div>
       <div><%= link_to "Contact", contact_path %></div>
       <div><%= link_to "Blogs", blogs_path %></div>
       <div><%= link_to "Portfolio", portfolios_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer > 
  <div class="container text-secondary">

    <center ><%= copyright_generator%> </center>
    <center><a href="#" class="small">Back To Top</a></center>
  </div>
</footer>

app/views/shared/_portfolio_header.html.erb
      <section class="jumbotron text-center section-bg"><!-- start of header -->
        <div class="container ">
            
       <%= image_tag "logo.png" , class: 'mb-2 portfolio-logo' %>

          <p class="lead text-muted secondary-font">Below are some of the projects that I have completed. These were the ones that I felt like I learned the most from. Please check them out and then head over to my blog to see my journey as web developer.</p>
          <p>
            <%= link_to 'More About Me', about_me_path, class: "btn btn-outline-primary my-2" %>
            <%= link_to 'My Blog', about_me_path, class: "btn btn-outline-dark my-2" %>
          </p>
        </div>
      </section><!-- end of header -->

app/views/shared/_portfolio_nav.html.erb
    <header><!-- start of navigation -->
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container"> <!-- start of container -->
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">About</h4>
              <p class="text-muted">Hello my name is Peter and I am a full-stack web developer. I spend anytime I can perfecting and sharpening my tool kit. I love learning new things and cannot picture myself doing anything else. For me it is not just a job, but something I do out of passion. I invariably put a hundred and ten percent in every project I work on, for I am grateful to be working in this field.   </p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Navigate</h4>
              <ul class="list-unstyled">
                <li><%= link_to "Home", root_path, class: "text-white" %></li>
                <li><%= link_to "About", about_me_path, class: "text-white" %></li>
                <li><%= link_to "Contact", contact_path, class: "text-white" %></li>
                <li><%= link_to "Tweets",  tech_news_path, class: 'text-white' %></li>
                <li><%= link_to "Blogs", blogs_path, class: "text-white" %></li>
                <li><%= link_to "Portfolio", portfolios_path, class: "text-white" %></li>
                <li><%= login_helper 'text-white' %></li>

              </ul>
            </div>
          </div>
        </div><!-- end of container -->
      </div>
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container d-flex justify-content-between">
          <a href="<%=root_path%>" class="navbar-brand d-flex align-items-center">
            <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
            <strong>Peter Tran</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header><!-- end of nav -->

 